### ISSUE TITLE
? for help

### ISSUE THREAD

**Issue by drewp** [mothepro/lit-sets#3]
2 low priority feature requests:

I forgot the keys, so I tried '?' to see the help box. (Nothing happened.)

I got the help box open, but the keyboard shortcuts are scrolled out of sight. I wish they were higher or in a separate popup.

**Comment by mothepro** [comment]
Oh good ideas, I pushed them out in [v0.0.6](https://github.com/mothepro/lit-sets/releases/tag/v0.0.6), thanks.
